version: 2.1

orbs:
  snyk: snyk/snyk@0.0.8
#  codecov: codecov/codecov@1.0.2

jobs:
  build:
    docker:
      - image: circleci/node:12.14.1-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn lint

      - run: yarn size

      #- run: npm test -- --coverage --watchAll=false --coerageDirectory=coverage
      - run: yarn test

      #- codecov/upload:
      #  file: "output/coverage-final.json"

      - snyk/scan:
          fail-on-issues: false
          monitor-on-build: false
          severity-threshold: high
